parameters:
  AgentPool : 'Win-CPU'
  DoDebugBuild: 'true'
  DoCompliance: 'false'
  BuildCommand: ''
  JobName: 'Windows_CI_Dev_x86'
  DoNugetPack:  'false'
  NuPackScript : ''
  DoEsrp: 'false'

jobs:
- job: ${{ parameters.JobName }}
  timeoutInMinutes: 120
  pool: ${{ parameters.AgentPool }}
  variables:
    buildDirectory: '$(Build.BinariesDirectory)'
    OnnxRuntimeBuildDirectory: '$(Build.BinariesDirectory)'
    BuildCommand: ${{ parameters.BuildCommand }}
    PlatformTarget: x86
    RuntimeIdentifier: win-x86
    DotNetExe: '"c:\program files (x86)\dotnet\dotnet.exe"'
  steps:
    - template: set-test-data-variables-step.yml
    - template: windows-build-tools-setup-steps.yml
      parameters:
        EnvSetupScript: 'setup_env.bat'
        buildArch: 'x86'
        setVcvars: false

    # Build Debug Mode
    - task: CmdLine@1
      displayName: 'Download test data and generate cmake config'
      inputs:
        filename: '$(Build.BinariesDirectory)\packages\python\python.exe'
        arguments: '$(BuildCommand) --update --config Debug RelWithDebInfo'
        workingDirectory: "$(Build.BinariesDirectory)"

    - ${{ if eq(parameters['DoDebugBuild'], 'true') }}:
      - task: VSBuild@1
        displayName: 'Build Debug'
        inputs:
          solution: '$(Build.BinariesDirectory)\Debug\onnxruntime.sln'
          platform: 'Win32'
          configuration: 'Debug'
          msbuildArguments: '/m'
          msbuildArchitecture: 'x86'
          logProjectEvents: true
          workingFolder: '$(Build.BinariesDirectory)\Debug'

      - task: BatchScript@1
        displayName: 'Test Debug'
        inputs:
          filename: '$(Build.BinariesDirectory)\packages\python\python.exe'
          arguments: '$(BuildCommand) --test --config Debug'
          workingFolder: '$(Build.BinariesDirectory)'

      - task: VSBuild@1
        displayName: 'Build C# Debug'
        inputs:
          solution: '$(Build.SourcesDirectory)\csharp\OnnxRuntime.CSharp.sln'
          platform: 'any cpu'
          configuration: 'Debug'
          restoreNugetPackages: false
          msbuildArchitecture: 'x86'
          workingFolder: '$(Build.SourcesDirectory)\csharp'
          msbuildArguments: '/m'

      - task: CmdLine@2
        displayName: 'Test C# Debug'
        inputs:
          script: |
           FOR /F  %%f IN ('dir /s /b test\Microsoft.ML.OnnxRuntime.Tests\bin\*Tests.dll') DO %dotnetexe% vstest %%f 
          workingDirectory: '$(Build.SourcesDirectory)\csharp'

    # Build RelWithDebInfo -- this variable required to build C#
    - task: CmdLine@2
      displayName: 'Set Configuration to RelWithDebInfo'
      inputs:
        script: |
         @echo ##vso[task.setvariable variable=Configuration;]RelWithDebInfo

    - task: VSBuild@1
      displayName: 'Build RelWithDebInfo'
      inputs:
        solution: '$(Build.BinariesDirectory)\RelWithDebInfo\onnxruntime.sln'
        platform: 'Win32'
        configuration: 'RelWithDebInfo'
        msbuildArguments: '/m'
        msbuildArchitecture: 'x86'
        logProjectEvents: true
        workingFolder: '$(Build.BinariesDirectory)\RelWithDebInfo'

    - task: BatchScript@1
      displayName: 'Test RelWithDebInfo'
      inputs:
        filename: '$(Build.BinariesDirectory)\packages\python\python.exe'
        arguments: '$(BuildCommand) --test --config RelWithDebInfo'
        workingFolder: "$(Build.BinariesDirectory)"

    - task: VSBuild@1
      displayName: 'Build C# RelWithDebInfo'
      inputs:
        solution: '$(Build.SourcesDirectory)\csharp\OnnxRuntime.CSharp.sln'
        platform: 'any cpu'
        configuration: 'RelWithDebInfo'
        msbuildArchitecture: 'x86'
        restoreNugetPackages: false
        workingFolder: '$(Build.SourcesDirectory)\csharp'
        msbuildArguments: '/m'

    - task: CmdLine@2
      displayName: 'Test C# RelWithDebInfo'
      inputs:
        script: |
         FOR /F  %%f IN ('dir /s /b test\Microsoft.ML.OnnxRuntime.Tests\bin\*Tests.dll') DO %dotnetexe% vstest %%f 
        workingDirectory: '$(Build.SourcesDirectory)\csharp'

    - task: PublishTestResults@2
      displayName: 'Publish unit test results'
      inputs:
        testResultsFiles: '**\*.results.xml'
        searchFolder: '$(Build.BinariesDirectory)'
        testRunTitle: 'Unit Test Run'
      condition: succeededOrFailed()

    # Nuget packaging if needed
    - ${{ if eq(parameters['DoNugetPack'], 'true') }}:
      - task: BatchScript@1
        displayName: 'Setup VS2017 env vars'
        inputs:
          filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
          arguments: 'x86 -vcvars_ver=14.11'
          modifyEnvironment: true

      # Esrp signing
      - template: esrp_dll.yml
        parameters:
          FolderPath: '$(Build.BinariesDirectory)\RelWithDebInfo'
          DisplayName: 'ESRP - Sign Native dlls'
          DoEsrp: ${{ parameters.DoEsrp }}

      - template: esrp_dll.yml
        parameters:
          FolderPath: '$(Build.SourcesDirectory)\csharp\src\Microsoft.ML.OnnxRuntime\bin\RelWithDebInfo'
          DisplayName: 'ESRP - Sign C# dlls'
          DoEsrp: ${{ parameters.DoEsrp }}

      - script: |
         ${{ parameters.NuPackScript }}
        workingDirectory: '$(Build.SourcesDirectory)\csharp'
        displayName: 'Create NuGet Package'

      - task: PublishPipelineArtifact@0
        displayName: 'Publish Pipeline Artifact: drop win x86 zip'
        inputs:
          artifactName: 'drop-win-x86-zip'
          targetPath: '$(Build.ArtifactStagingDirectory)'

    - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
      displayName: 'Component Detection'
      condition: succeeded()

    - template: clean-agent-build-directory-step.yml
