jobs:
- template: templates/win-ci.yml
  parameters:
    AgentPool : 'Win-GPU-CUDA10'
    DoDebugBuild: 'true'
    DoCompliance: 'false'
    BuildCommand: '$(Build.SourcesDirectory)\tools\ci_build\build.py --build_dir $(Build.BinariesDirectory) --skip_submodule_sync --cmake_path $(Build.BinariesDirectory)\cmake\bin\cmake.exe --ctest_path $(Build.BinariesDirectory)\cmake\bin\ctest.exe  --enable_pybind --use_openmp --use_mkldnn --use_mkldnn --build_shared_lib  --build_csharp --enable_onnx_tests --use_cuda --cuda_home="C:\local\cuda_10.0.130_win10" --cudnn_home="C:\local\cudnn-10.0-windows10-x64-v7.3.1.20\cuda" --test_data_url $(TestDataUrl) --test_data_checksum $(TestDataChecksum) --msvc_toolset=14.11'
    JobName: 'Windows_CI_GPU_Dev'
    DoNugetPack:  'false'
    NuPackScript : ''
    DoTestCoverage: 'false'
    BuildArch: 'amd64'
    SetVcvars: 'true'
    MsbuildArguments: '/m /p:CudaToolkitDir=C:\local\cuda_10.0.130_win10\'
    EnvSetupScript: 'setup_env_cuda.bat'
    CudaVersion: '10.0'
